ishod_2/dpetrec_i2/Controllers/PohadanjePredmetaController.cs
using dpetrec_i2.Repos;
using dpetrec_i2.Repos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dpetrec_i2.Controllers
{
    public class PohadanjePredmetaController : Controller
    {
        StudentDbCont db = new StudentDbCont();
        // GET: PohadanjePredmetaController
        public ActionResult Index()
        {
            return View(db.PohadanjePredmeta.ToList());
        }

        // GET: PohadanjePredmetaController/Details/5
        public ActionResult Details(int id)
        {
            PohadanjePredmeta predmetPoh = db.PohadanjePredmeta.Find(id);
            if (predmetPoh == null)
            {
                return RedirectToAction("Home");
            }
            return View(predmetPoh);
        }

        // GET: PohadanjePredmetaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PohadanjePredmetaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PohadanjePredmeta predmetPoh)
        {
            if (ModelState.IsValid)
            {
                db.PohadanjePredmeta.Add(predmetPoh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(predmetPoh);
        }

        // GET: PohadanjePredmetaController/Edit/5
        public ActionResult Edit(int id)
        {
            PohadanjePredmeta predmetPoh = db.PohadanjePredmeta.Find(id);
            if (predmetPoh == null)
            {
                RedirectToAction("Index");
            }
            return View(predmetPoh);
        }

        // POST: PohadanjePredmetaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PohadanjePredmeta predmetPoh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(predmetPoh).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(predmetPoh);
        }

        // GET: PohadanjePredmetaController/Delete/5
        public ActionResult Delete(int id)
        {
            var predmetPoh = db.PohadanjePredmeta.Where(x => x.ID == id).FirstOrDefault();
            if (predmetPoh == null)
            {
                return RedirectToAction("Index");
            }
            return View(predmetPoh);
        }

        // POST: PohadanjePredmetaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePohPred(int id)
        {
            var predmetPoh = db.PohadanjePredmeta.Find(id);
            db.PohadanjePredmeta.Remove(predmetPoh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ishod_2/dpetrec_i2/Controllers/PredmetController.cs
using dpetrec_i2.Repos;
using dpetrec_i2.Repos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dpetrec_i2.Controllers
{
    public class PredmetController : Controller
    {
        StudentDbCont db = new StudentDbCont();
        // GET: PredmetController
        public ActionResult Index()
        {
            return View(db.Predmet.ToList());
        }

        // GET: PredmetController/Details/5
        public ActionResult Details(int id)
        {
            Predmet predmet = db.Predmet.Find(id);
            if (predmet == null)
            {
                return RedirectToAction("Home");
            }
            return View(predmet);
        }

        // GET: PredmetController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PredmetController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                db.Predmet.Add(predmet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(predmet);
        }

        // GET: PredmetController/Edit/5
        public ActionResult Edit(int id)
        {
            Predmet predmet = db.Predmet.Find(id);
            if (predmet == null)
            {
                RedirectToAction("Index");
            }
            return View(predmet);
        }

        // POST: PredmetController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(predmet).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(predmet);
        }

        // GET: PredmetController/Delete/5
        public ActionResult Delete(int id)
        {
            var predmet = db.Predmet.Where(x => x.ID == id).FirstOrDefault();
            
            if (predmet == null)
            {
                return RedirectToAction("Index");
            }
            return View(predmet);
        }

        // POST: PredmetController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePredmet(int id)
        {
            var predmet = db.Predmet.Find(id);
            
            db.Predmet.Remove(predmet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ishod_2/dpetrec_i2/Controllers/StudentController.cs
using dpetrec_i2.Repos;
using dpetrec_i2.Repos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dpetrec_i2.Controllers
{
    public class StudentController : Controller
    {
        StudentDbCont db = new StudentDbCont();
        // GET: StudentController
        public ActionResult Index()
        {
            return View(db.Student.ToList());

        }

        // GET: StudentController/Details/5
        public ActionResult Details(int id)
        {
            Student student = db.Student.Find(id);
            if (student == null)
            {
                return RedirectToAction("Home");
            }
            return View(student);
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Student student)
        {
            if (ModelState.IsValid)
            {
                db.Student.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: StudentController/Edit/5
        public ActionResult Edit(int id)
        {
            Student student = db.Student.Find(id);
            if (student == null)
            {
                RedirectToAction("Index");
            }
            return View(student);
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(student);
        }

        // GET: StudentController/Delete/5
        public ActionResult Delete(int id)
        {
            var student = db.Student.Where(x => x.ID == id).FirstOrDefault();
            if (student == null)
            {
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // POST: StudentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteStudent(int id)
        {
            var student = db.Student.Find(id);
            db.Student.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ishod_2/dpetrec_i2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dpetrec_i2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dpetrec_i2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predmet" asp-action="Index">Predmeti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PohadanjePredmeta" asp-action="Index">Pohadanje Predmeta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - dpetrec_i2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>